### ISSUE TITLE
Error in answer for a given random number Partition02.pg

### ISSUE THREAD

**Issue by murphywaggoner** [openwebwork/webwork-open-problem-library#663] opened 2020-01-05 07:39 UTC
Forgive me if this is not the right forum for this or the wrong way to point out an error in a particular problem.

In the problem [Partition02.pg](https://github.com/openwebwork/webwork-open-problem-library/blob/ee2330e92fbbd7d28d1fd4733377055e0c5d7a2b/OpenProblemLibrary/MC/Proofs/Relations/Partition02.pg), the randomization is 

`$n = random(11,23,2);`

however, when `$n = 11`, the selection 

`"\(S_0 =\){0},\(S_1 =\){3,6,9},\(S_2 =\){1,4,7,10},\(S_3 =\){2,5,8,11},\(A - S_0 - S_1 - S_2 - S_3\)",`

is not a partition since `\(A - S_0 - S_1 - S_2 - S_3\`) will be the empty set.

**Comment by jwj61** [comment] 2020-01-05 15:30
Most bugs go through bugzilla, but it is ok to report them here as well.

When reporting a bug, you should give the full path to the problem.  Many pg files have the same filename, although there is only one in this case.

In any case, the bug is now fixed (I removed an element from S_3).

**Closed by jwj61** 2020-01-05 15:30 UTC

**Comment by murphywaggoner** [comment] 2020-01-05 19:03
The entire path to the problem is in the link in the message. Should I have included it as text as well? I couldn’t find a way to report a problem from inside WeBWorK. I thought there was a “report a problem” link there.
thank you


Preferred pronouns: she/her/hers

**Comment by jwj61** [comment] 2020-01-05 19:06
Including as text is better, and with that, you don't need the link.  Anyone fixing the bug will need to look at the file on their own computer, not on github.

I am pretty sure there is an option to decide what user level sees the report bug link in the sidebar.

**Comment by mgage** [comment] 2020-01-05 21:17
"report bugs in this problem" is a button in the upper right on the problem editor page -- where you edit problems.  If the problem you are reporting is a library problem it automatically includes the path to the problem in the library and the problemSeed that caused the trouble.  If the problem is one that you have authored you need to include the text of the problem (and the seed) in the report in order to get help with the bug.  Thanks for reporting these bugs -- every single squashed bug helps.
