### ISSUE TITLE
Library/274/systems/prob001.pg - round coefficients close to zero

### ISSUE THREAD

**Issue by timkato** [openwebwork/webwork-open-problem-library#255] opened 2016-09-12 21:51 UTC
http://bugs.webwork.maa.org/show_bug.cgi?id=3581 

I found a bug in the source file '[TMPL]/Library/274/systems/prob001.pg'//when
the random seed is 4555.
The answer to part 3 should be x(t)=9exp(-0.9t) and y(t)=6exp(-0.9t) but the
system gives the "correct answer" as attached. This problem only appears with
this random seed and it works fine for other students.

Comment #1 From John Jones 2016-06-16 14:45:18
Coefficients close to zero needed to be rounded off

@xcompass

**Comment by jwj61** [comment] 2016-09-12 22:48
I don't understand this issue.  The bug from bugzilla is marked as fixed, and the suggested correct answers for the given seed work.  So why is this an issue?

**Comment by xcompass** [comment] 2016-09-12 23:05
Could be because we didn't pull in the change. Let me double check.

**Comment by jwj61** [comment] 2016-09-15 19:49
Closing since it has been a few days.  If there is a problem, bugzilla is probably the better place to report it right now.

**Closed by jwj61** 2016-09-15 19:49 UTC

**Comment by xcompass** [comment] 2016-09-19 05:14
Sorry for the delay. I can confirm it works after pulling in the updates. Thanks.
